name: Pull Request
on: 
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Assign assignees
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"assignees": ["pascal-beaulne"]}' \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees